# Generated by Django 2.0.1 on 2018-01-06 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid_token', models.CharField(max_length=16)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('team', models.CharField(choices=[('B', 'Bride'), ('G', 'Groom')], max_length=1)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('adult', models.BooleanField(default=False)),
                ('groom_relative', models.BooleanField(default=False)),
                ('bride_relative', models.BooleanField(default=False)),
            ],
        ),
    ]
