# Generated by Django 2.0.1 on 2018-01-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wgserver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rule',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.CharField(choices=[('N', 'Unassigned'), ('B', 'Bride'), ('G', 'Groom')], max_length=1),
        ),
    ]
